# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: Vars

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Bash@3
  inputs:
      targetType: "inline"
      script: 'sh -c "$(curl -fsSL https://get.testcontainers.cloud/bash)"'
  env:
      TC_CLOUD_TOKEN: '$(TC_CLOUD_TOKEN)'

- task: DotNetCoreCLI@2
  displayName: 'Run tests using Testcontainers Cloud'
  inputs:
    command: 'test'
    projects: 'PlaywrightExample/*[Tt]ests/*.csproj' # Dostosuj do struktury projektu
    arguments: '--configuration $(buildConfiguration) --no-build --logger "trx;LogFileName=test-results.trx"'
  # Zmienna TESTCONTAINERS_CLOUD_TOKEN jest automatycznie dostępna tutaj jako zmienna środowiskowa
  # dzięki zlinkowaniu Variable Group w sekcji 'variables' na górze pliku.
  # Można by ją też jawnie zmapować w sekcji 'env:', ale zazwyczaj nie jest to konieczne:
  # env:
  #   TESTCONTAINERS_CLOUD_TOKEN: $(TESTCONTAINERS_CLOUD_TOKEN)

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  condition: succeededOrFailed()
  # ... reszta konfiguracji PublishTestResults ...
